#!/usr/bin/env php
<?php

/**
 * debugger – MinecraftPacketDebugger
 *
 * Copyright (C) 2019 Jack Noordhuis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author Jack
 *
 */

declare(strict_types=1);

require_once file_exists(__DIR__.'/vendor/autoload.php') ?  __DIR__.'/vendor/autoload.php' : __DIR__.'/../../autoload.php';

($app = new Symfony\Component\Console\Application())->addCommands([
	new jacknoordhuis\minecraftpacketdebugger\cli\commands\StartSimpleDebugProxy
]);

$app->setDefaultCommand("simple");

$app->run();